ldap:
  image: dcm4che/slapd-dcm4chee:5.0.1
  ports:
    - "1389:389"
  environment:
    LDAP_BASE_DN: dc=mycorp,dc=com
    LDAP_ORGANISATION: My Mega Corporation
    LDAP_ROOTPASS: mysecret
    LDAP_CONFIGPASS: myconfigsecret
    DEVICE_NAME: my-pacs
    AE_TITLE: MYPACS
    DICOM_HOST: localhost
    DICOM_PORT: 11112
    HL7_PORT: 2575
    STORAGE_DIR: /var/local/mypacs/storage
  volumes:
    - /var/local/mypacs/ldap:/var/lib/ldap
    - /var/local/mypacs/slapd.d:/etc/ldap/slapd.d
db:
  image: dcm4che/postgres-dcm4chee:5.0.1
  ports:
    - "15432:5432"
  environment:
    POSTGRES_DB: pacsdb
    POSTGRES_USER: pacs
    POSTGRES_PASSWORD: pacsword
  volumes:
    - /var/local/mypacs/db:/var/lib/postgresql/data
mypacs:
  image: dcm4che/dcm4chee-arc-psql:5.0.1-secure-ui
  ports:
    - "8080:8080"
    - "9990:9990"
    - "11112:11112"
    - "2575:2575"
  links:
    - ldap:ldap
    - db:db
  volumes:
    - /var/local/mypacs/storage:/var/local/mypacs/storage
    - /var/local/mypacs/log:/opt/wildfly/standalone/log
    - /tmp:/opt/wildfly/standalone/tmp
