version: "2"
services:
  slapd:
    image: dcm4che/slapd-dcm4chee:2.4.44-10.5
    ports:
      - "389:389"
    env_file: docker-compose.env
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/local/dcm4chee-arc/ldap:/var/lib/ldap
      - /var/local/dcm4chee-arc/slapd.d:/etc/ldap/slapd.d
  postgres:
    image: dcm4che/postgres-dcm4chee:9.6-10
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/local/dcm4chee-arc/db:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:5.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/local/dcm4chee-arc/elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: kibana:5.5.1
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
  logstash:
    image: dcm4che/logstash-dcm4chee:5.5.1-3
    ports:
      - "12201:12201/udp"
      - "8514:8514/udp"
      - "8514:8514"
    links:
      - elasticsearch:elasticsearch
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
  keycloak:
    image: dcm4che/keycloak:3.2.1-1-logstash
    ports:
      - "8880:8880"
      - "8843:8843"
      - "8990:8990"
    env_file: docker-compose.env
    environment:
      HTTP_PORT: 8880
      HTTPS_PORT: 8843
      MANAGEMENT_HTTP_PORT: 8990
      KEYCLOAK_WAIT_FOR: ldap:389 logstash:8514
    links:
      - slapd:ldap
      - logstash:logstash
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/local/dcm4chee-arc/keycloak:/opt/keycloak/standalone
  dcm4chee-arc:
    image: dcm4che/dcm4chee-arc-psql:5.10.5-logstash-secure-ui
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "11112:11112"
      - "2575:2575"
    env_file: docker-compose.env
    environment:
      HTTP_PORT: 8080
      HTTPS_PORT: 8443
      MANAGEMENT_HTTP_PORT: 9990
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432 logstash:8514
      UI_CLIENT_ID: dcm4chee-arc-ui
    links:
      - slapd:ldap
      - postgres:db
      - logstash:logstash
      - keycloak:keycloak
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/local/dcm4chee-arc/storage:/storage
      - /var/local/dcm4chee-arc/wildfly:/opt/wildfly/standalone
  keycloak-proxy:
    image: dcm4che/keycloak-proxy:3.2.1-1
    ports:
      - "8601:8601"
      - "8643:8643"
    env_file: docker-compose.env
    environment:
      HTTP_PORT: 8601
      HTTPS_PORT: 8643
      TARGET_URL: http://gunter-nb:5601
      CLIENT_ID: kibana
      ROLE_ALLOWED: auditlog
    links:
      - kibana:kibana
      - keycloak:keycloak
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
